//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Want.RecordEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Want.RecordEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap pagenext {
            get {
                object obj = ResourceManager.GetObject("pagenext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pageprevious {
            get {
                object obj = ResourceManager.GetObject("pageprevious", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@want.ch.
        /// </summary>
        internal static string smtp_recepient {
            get {
                return ResourceManager.GetString("smtp_recepient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mail.netzone.ch.
        /// </summary>
        internal static string smtp_server {
            get {
                return ResourceManager.GetString("smtp_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:ns=&quot;http://www.want.ch/fillred&quot;&gt;
        ///  
        ///  &lt;xsl:template match=&quot;ns:LayoutDataset&quot;&gt;
        ///    &lt;LayoutDataset xmlns=&quot;http://www.want.ch/fillred&quot;&gt;
        ///      &lt;xsl:apply-templates select=&quot;ns:Record&quot;&gt;
        ///        &lt;xsl:sort select=&quot;ns:Name&quot;/&gt;
        ///      &lt;/xsl:apply-templates&gt;
        ///      &lt;xsl:apply-templates select=&quot;ns:Field&quot;&gt;
        ///        &lt;xsl:sort select=&quot;ns:RecordName&quot;/&gt;
        ///        &lt;xsl:sort select=&quot;ns:Index&quot; data-t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sortlayout {
            get {
                return ResourceManager.GetString("sortlayout", resourceCulture);
            }
        }
    }
}
